### ISSUE TITLE
Show annotation on graphs

### ISSUE THREAD

**Issue by quique05** [QuriQuant/qq-pat#2]
It would be very useful to be able to note some comments on graphs. For example: annotating buy or sell signals

**Comment by danielfppps** [comment]
Since the library is not aware of any trade structure but simply aware of the returns it does not know when you entered buy or sell trades and therefore cannot annotate in this manner.

However I will add a figure return to the plots so that you can then add anything you wish if you do not want to save the plot as output initially by the library.
